/*
 * CRYSTALS-Dilithium3 (ML-DSA-65) parameters
 * Vendored from pq-crystals/dilithium reference implementation (public domain)
 */
#ifndef DILITHIUM_PARAMS_H
#define DILITHIUM_PARAMS_H

#define DILITHIUM_N 256
#define DILITHIUM_Q 8380417
#define DILITHIUM_D 13
#define DILITHIUM_ROOT_OF_UNITY 1753

/* Dilithium3 (ML-DSA-65) parameters */
#define DILITHIUM_K 6
#define DILITHIUM_L 5
#define DILITHIUM_ETA 4
#define DILITHIUM_TAU 49
#define DILITHIUM_BETA 196
#define DILITHIUM_GAMMA1 (1 << 19)
#define DILITHIUM_GAMMA2 ((DILITHIUM_Q-1)/32)
#define DILITHIUM_OMEGA 55

#define DILITHIUM_POLYT1_PACKEDBYTES  320
#define DILITHIUM_POLYT0_PACKEDBYTES  416
#define DILITHIUM_POLYVECH_PACKEDBYTES (DILITHIUM_OMEGA + DILITHIUM_K)

#define DILITHIUM_POLYETA_PACKEDBYTES  128
#define DILITHIUM_POLYZ_PACKEDBYTES    640
#define DILITHIUM_POLYW1_PACKEDBYTES   128

#define DILITHIUM_SEEDBYTES  32
#define DILITHIUM_CRHBYTES   64
#define DILITHIUM_TRBYTES    64
#define DILITHIUM_CTILDEBYTES 48   /* FIPS 204: challenge seed length for ML-DSA-65 */
#define DILITHIUM_RNDBYTES   32    /* FIPS 204: randomized signing hedging bytes */

#define DILITHIUM_CRYPTO_PUBLICKEYBYTES (DILITHIUM_SEEDBYTES + DILITHIUM_K*DILITHIUM_POLYT1_PACKEDBYTES)
/* 32 + 6*320 = 1952 */
#define DILITHIUM_CRYPTO_SECRETKEYBYTES (2*DILITHIUM_SEEDBYTES \
    + DILITHIUM_TRBYTES \
    + DILITHIUM_L*DILITHIUM_POLYETA_PACKEDBYTES \
    + DILITHIUM_K*DILITHIUM_POLYETA_PACKEDBYTES \
    + DILITHIUM_K*DILITHIUM_POLYT0_PACKEDBYTES)
/* 32 + 32 + 64 + 5*128 + 6*128 + 6*416 = 4032 */
#define DILITHIUM_CRYPTO_BYTES (DILITHIUM_CTILDEBYTES \
    + DILITHIUM_L*DILITHIUM_POLYZ_PACKEDBYTES \
    + DILITHIUM_POLYVECH_PACKEDBYTES)
/* 48 + 5*640 + 61 = 3309 */

#endif /* DILITHIUM_PARAMS_H */
