/*
 * CRYSTALS-Kyber768 parameters
 * Vendored from pq-crystals/kyber reference implementation (public domain)
 */
#ifndef KYBER_PARAMS_H
#define KYBER_PARAMS_H

#define KYBER_K 3

#define KYBER_N 256
#define KYBER_Q 3329

#define KYBER_SYMBYTES 32   /* size of hashes, seeds */
#define KYBER_SSBYTES  32   /* size of shared key */

#define KYBER_POLYBYTES     384
#define KYBER_POLYVECBYTES  (KYBER_K * KYBER_POLYBYTES)

#define KYBER_ETA1 2
#define KYBER_ETA2 2

#define KYBER_POLYCOMPRESSEDBYTES    128
#define KYBER_POLYVECCOMPRESSEDBYTES (KYBER_K * 320)

#define KYBER_INDCPA_MSGBYTES       (KYBER_SYMBYTES)
#define KYBER_INDCPA_PUBLICKEYBYTES (KYBER_POLYVECBYTES + KYBER_SYMBYTES)
#define KYBER_INDCPA_SECRETKEYBYTES (KYBER_POLYVECBYTES)
#define KYBER_INDCPA_BYTES          (KYBER_POLYVECCOMPRESSEDBYTES + KYBER_POLYCOMPRESSEDBYTES)

#define KYBER_PUBLICKEYBYTES  (KYBER_INDCPA_PUBLICKEYBYTES)
/* 1184 bytes */
#define KYBER_SECRETKEYBYTES  (KYBER_INDCPA_SECRETKEYBYTES + KYBER_INDCPA_PUBLICKEYBYTES + 2*KYBER_SYMBYTES)
/* 2400 bytes */
#define KYBER_CIPHERTEXTBYTES (KYBER_INDCPA_BYTES)
/* 1088 bytes */

#endif /* KYBER_PARAMS_H */
