/*
 * Exit-notice HTTP server. Modeled on Tor's DirPortFrontPage: when someone
 * hits the exit IP's port 80 directly (abuse complaints, curious visitors,
 * scanners), they see a human-readable notice instead of a refused
 * connection.  Static response, no request parsing beyond dropping the
 * received bytes.
 */
#include "moor/moor.h"
#include "moor/exit_notice.h"
#include "moor/event.h"

#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>

static int  g_listen_fd = -1;
static char g_body[2048];
static size_t g_body_len = 0;
static char g_headers[256];
static size_t g_headers_len = 0;

static void set_nonblock(int fd) {
    int fl = fcntl(fd, F_GETFL, 0);
    if (fl >= 0) fcntl(fd, F_SETFL, fl | O_NONBLOCK);
}

static void build_page(const char *nickname, const char *contact,
                       const char *build_id) {
    const char *nn = (nickname && nickname[0]) ? nickname : "anonymous";
    const char *ci = (contact  && contact[0])  ? contact  : "(not configured)";
    const char *bi = (build_id && build_id[0]) ? build_id : "unknown";

    g_body_len = (size_t)snprintf(g_body, sizeof(g_body),
        "<!DOCTYPE html>\n"
        "<html><head><meta charset=\"utf-8\">"
        "<title>MOOR exit relay</title>"
        "<style>body{font-family:monospace;max-width:720px;margin:3em auto;"
        "padding:0 1em;color:#ddd;background:#111;line-height:1.5}"
        "h1{color:#fff;border-bottom:1px solid #444;padding-bottom:.3em}"
        "code{background:#222;padding:.1em .3em;border-radius:2px}"
        "a{color:#6af}</style></head><body>"
        "<h1>This is a MOOR exit relay.</h1>"
        "<p>You're looking at the public IP of a node in the "
        "<a href=\"https://github.com/0xdeadbeefnetwork\">MOOR</a> "
        "anonymous overlay network. Outbound traffic from this host is "
        "generated by other users whose identity and location this operator "
        "cannot see.</p>"
        "<p>If you believe traffic from this IP was abusive, the operator "
        "can confirm that it originated through the MOOR network but "
        "cannot identify the sender. MOOR is a Tor-style design: no logs, "
        "no metadata, no exceptions.</p>"
        "<h2>Node info</h2>"
        "<ul>"
        "<li>nickname: <code>%s</code></li>"
        "<li>operator contact: <code>%s</code></li>"
        "<li>build: <code>%s</code></li>"
        "</ul>"
        "<p style=\"color:#888;font-size:.9em\">Nothing else is served on "
        "this port. Port 80 on this host is not a web server.</p>"
        "</body></html>\n",
        nn, ci, bi);

    g_headers_len = (size_t)snprintf(g_headers, sizeof(g_headers),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html; charset=utf-8\r\n"
        "Content-Length: %zu\r\n"
        "Connection: close\r\n"
        "Cache-Control: no-store\r\n"
        "\r\n",
        g_body_len);
}

static void client_read_cb(int fd, int events, void *arg) {
    (void)events; (void)arg;
    char buf[1024];
    /* Drain whatever the client sent — we don't parse the request. */
    ssize_t n = recv(fd, buf, sizeof(buf), 0);
    if (n <= 0) {
        moor_event_remove(fd);
        close(fd);
        return;
    }
    /* One shot: send headers + body then close. */
    (void)send(fd, g_headers, g_headers_len, MSG_NOSIGNAL);
    (void)send(fd, g_body,    g_body_len,    MSG_NOSIGNAL);
    moor_event_remove(fd);
    close(fd);
}

static void accept_cb(int fd, int events, void *arg) {
    (void)events; (void)arg;
    struct sockaddr_storage ss;
    socklen_t sl = sizeof(ss);
    int cfd = accept(fd, (struct sockaddr *)&ss, &sl);
    if (cfd < 0) return;
    set_nonblock(cfd);
    moor_event_add(cfd, MOOR_EVENT_READ, client_read_cb, NULL);
}

int moor_exit_notice_start(const char *nickname, const char *contact_info,
                           const char *build_id) {
    if (g_listen_fd >= 0) return 0;  /* idempotent */

    int s = socket(AF_INET, SOCK_STREAM, 0);
    if (s < 0) return -1;
    int one = 1;
    setsockopt(s, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
    set_nonblock(s);

    struct sockaddr_in sin;
    memset(&sin, 0, sizeof(sin));
    sin.sin_family = AF_INET;
    sin.sin_port = htons(80);
    sin.sin_addr.s_addr = htonl(INADDR_ANY);

    if (bind(s, (struct sockaddr *)&sin, sizeof(sin)) != 0) {
        /* EADDRINUSE: some other web server already owns :80 — fine.
         * EACCES:     no CAP_NET_BIND_SERVICE — also fine, just skip. */
        if (errno != EADDRINUSE && errno != EACCES) {
            LOG_DEBUG("exit-notice: bind :80 failed: %s", strerror(errno));
        } else {
            LOG_INFO("exit-notice: port 80 unavailable (%s), skipping",
                     strerror(errno));
        }
        close(s);
        return -1;
    }
    if (listen(s, 32) != 0) {
        close(s);
        return -1;
    }

    build_page(nickname, contact_info, build_id);
    moor_event_add(s, MOOR_EVENT_READ, accept_cb, NULL);
    g_listen_fd = s;
    LOG_INFO("exit-notice: serving on :80 (/)");
    return 0;
}
