/*
 * Exit-notice HTTP server. Modeled on Tor's DirPortFrontPage: when someone
 * hits the exit IP's port 80 directly (abuse complaints, curious visitors,
 * scanners), they see a human-readable notice instead of a refused
 * connection.  Static response, no request parsing beyond dropping the
 * received bytes.
 */
#include "moor/moor.h"
#include "moor/exit_notice.h"
#include "moor/event.h"

#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>

static int  g_listen_fd = -1;
static char g_body[4096];
static size_t g_body_len = 0;
static char g_headers[256];
static size_t g_headers_len = 0;

static void set_nonblock(int fd) {
    int fl = fcntl(fd, F_GETFL, 0);
    if (fl >= 0) fcntl(fd, F_SETFL, fl | O_NONBLOCK);
}

static void build_page(const char *nickname, const char *contact,
                       const char *build_id) {
    const char *nn = (nickname && nickname[0]) ? nickname : "UNKNOWN";
    const char *ci = (contact  && contact[0])  ? contact  : "[REDACTED]";
    const char *bi = (build_id && build_id[0]) ? build_id : "unknown";
    uint64_t epoch = (uint64_t)time(NULL);

    g_body_len = (size_t)snprintf(g_body, sizeof(g_body),
        "<!DOCTYPE html>\n"
        "<html><head><meta charset=\"utf-8\">"
        "<title>// MOOR EXIT // %s //</title>"
        "<style>"
        "html,body{margin:0;padding:0;background:#000;color:#0f0;"
        "font-family:'Courier New',monospace;font-size:14px;line-height:1.4}"
        "body{padding:2em 1em;max-width:880px;margin:0 auto}"
        "pre{margin:0;white-space:pre-wrap;word-break:break-word}"
        ".dim{color:#060}.warn{color:#fa0}.hot{color:#f33}.key{color:#0ff}"
        ".blink{animation:b 1s steps(2) infinite}"
        "@keyframes b{50%%{opacity:0}}"
        "a{color:#0ff;text-decoration:none;border-bottom:1px dotted #0ff}"
        "a:hover{background:#0ff;color:#000}"
        "hr{border:0;border-top:1px dashed #050;margin:1em 0}"
        "::selection{background:#0f0;color:#000}"
        "</style></head><body><pre>"
        "<span class=\"dim\">"
        " __  __  ___   ___  ____     __                     _   _\n"
        "|  \\/  |/ _ \\ / _ \\|  _ \\   / _|    ___ __  _(_) |_\n"
        "| |\\/| | | | | | | | |_) | |  _|   / _ \\ \\/ / |  _|\n"
        "| |  | | |_| | |_| |  _ &lt;  |  _|  |  __/&gt;  &lt;| | |_\n"
        "|_|  |_|\\___/ \\___/|_| \\_\\ |_|     \\___/_/\\_\\_|\\__|\n"
        "</span>\n"
        "<span class=\"warn\">[!]</span> <span class=\"hot\">CONNECTION FLAGGED</span> "
        "<span class=\"blink\">_</span>\n"
        "<hr>"
        "you reached port <span class=\"key\">80</span> on a node of the "
        "<a href=\"https://github.com/0xdeadbeefnetwork\">MOOR</a> network.\n"
        "this is not a web server. this is a <span class=\"warn\">"
        "packet plumbing device</span> for an anonymous overlay.\n\n"
        "outbound traffic you saw from this IP was generated by somebody\n"
        "else — routed through three layers of encryption, bounced through\n"
        "two other countries, and emitted here. the operator of this box\n"
        "cannot see who they are. neither can you. neither can your lawyer.\n"
        "<hr>"
        "<span class=\"dim\">$</span> whois <span class=\"key\">this-host</span>\n"
        "  <span class=\"dim\">role    </span> :: exit relay\n"
        "  <span class=\"dim\">callsign</span> :: <span class=\"key\">%s</span>\n"
        "  <span class=\"dim\">build   </span> :: %s\n"
        "  <span class=\"dim\">contact </span> :: %s\n"
        "  <span class=\"dim\">epoch   </span> :: %llu\n"
        "<hr>"
        "<span class=\"dim\">$</span> cat <span class=\"key\">/var/log/who-sent-that</span>\n"
        "  <span class=\"hot\">cat: /var/log/who-sent-that: No such file or directory</span>\n"
        "  <span class=\"dim\"># MOOR does not keep traffic logs. not a policy choice.</span>\n"
        "  <span class=\"dim\"># the data isn't available to log. see the spec for why.</span>\n"
        "<hr>"
        "<span class=\"dim\">$</span> man <span class=\"key\">abuse-complaint</span>\n"
        "  if packets from this IP landed in your SIEM, grep, or inbox,\n"
        "  the operator CAN confirm this is a MOOR exit.\n"
        "  the operator <span class=\"hot\">WILL NOT</span> remove the exit flag. "
        "not for you.\n"
        "  not for your lawyer. not for your ISP. that is the <span class=\"warn\">"
        "threat model</span>,\n"
        "  not a bug. the operator CANNOT identify the origin — nobody can.\n"
        "  <span class=\"dim\"># filter our /24 if it bothers you. we won't take it personally.</span>\n"
        "<hr>"
        "<span class=\"dim\">[ nothing else is served on port 80. move along. ]</span>\n"
        "</pre></body></html>\n",
        nn, nn, bi, ci, (unsigned long long)epoch);

    g_headers_len = (size_t)snprintf(g_headers, sizeof(g_headers),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html; charset=utf-8\r\n"
        "Content-Length: %zu\r\n"
        "Connection: close\r\n"
        "Cache-Control: no-store\r\n"
        "\r\n",
        g_body_len);
}

static void client_read_cb(int fd, int events, void *arg) {
    (void)events; (void)arg;
    char buf[1024];
    /* Drain whatever the client sent — we don't parse the request. */
    ssize_t n = recv(fd, buf, sizeof(buf), 0);
    if (n <= 0) {
        moor_event_remove(fd);
        close(fd);
        return;
    }
    /* One shot: send headers + body then close. */
    (void)send(fd, g_headers, g_headers_len, MSG_NOSIGNAL);
    (void)send(fd, g_body,    g_body_len,    MSG_NOSIGNAL);
    moor_event_remove(fd);
    close(fd);
}

static void accept_cb(int fd, int events, void *arg) {
    (void)events; (void)arg;
    struct sockaddr_storage ss;
    socklen_t sl = sizeof(ss);
    int cfd = accept(fd, (struct sockaddr *)&ss, &sl);
    if (cfd < 0) return;
    set_nonblock(cfd);
    moor_event_add(cfd, MOOR_EVENT_READ, client_read_cb, NULL);
}

int moor_exit_notice_start(const char *nickname, const char *contact_info,
                           const char *build_id) {
    if (g_listen_fd >= 0) return 0;  /* idempotent */

    int s = socket(AF_INET, SOCK_STREAM, 0);
    if (s < 0) return -1;
    int one = 1;
    setsockopt(s, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
    set_nonblock(s);

    struct sockaddr_in sin;
    memset(&sin, 0, sizeof(sin));
    sin.sin_family = AF_INET;
    sin.sin_port = htons(80);
    sin.sin_addr.s_addr = htonl(INADDR_ANY);

    if (bind(s, (struct sockaddr *)&sin, sizeof(sin)) != 0) {
        /* EADDRINUSE: some other web server already owns :80 — fine.
         * EACCES:     no CAP_NET_BIND_SERVICE — also fine, just skip. */
        if (errno != EADDRINUSE && errno != EACCES) {
            LOG_DEBUG("exit-notice: bind :80 failed: %s", strerror(errno));
        } else {
            LOG_INFO("exit-notice: port 80 unavailable (%s), skipping",
                     strerror(errno));
        }
        close(s);
        return -1;
    }
    if (listen(s, 32) != 0) {
        close(s);
        return -1;
    }

    build_page(nickname, contact_info, build_id);
    moor_event_add(s, MOOR_EVENT_READ, accept_cb, NULL);
    g_listen_fd = s;
    LOG_INFO("exit-notice: serving on :80 (/)");
    return 0;
}
